[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
